/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiKeyResponse { 
    id: string;
    projectId: string;
    name: string;
    /**
     * Public prefix used for identifying the key
     */
    prefix: string;
    revoked: boolean;
    revokedAt?: string;
    expiresAt?: string;
    lastUsedAt?: string;
    createdBy?: string;
    createdAt: string;
}

