/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplyImprovementRequest { 
    /**
     * The improved prompt content to apply
     */
    improvedContent: string;
    /**
     * User applying the improvement
     */
    author: string;
}

