/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditResponse { 
    id?: string;
    /**
     * Event type (e.g., prompt.created, workflow.approved, scan.completed)
     */
    action?: string;
    /**
     * Resource category (prompt, workflow, scan)
     */
    resourceType?: string;
    resourceId?: string;
    resourceVersion?: number;
    actorUserId?: string;
    /**
     * Contextual event details
     */
    details?: { [key: string]: any; };
    timestamp?: string;
}

