/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './user-response.model';


export interface AuthResponse { 
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token (longer-lived)
     */
    refreshToken: string;
    /**
     * Access token expiration time in seconds
     */
    expiresIn?: number;
    user: UserResponse;
}

