/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Format of the prompt content
 */
export const ContentFormat = {
    Text: 'TEXT',
    Json: 'JSON',
    Yaml: 'YAML',
    Markdown: 'MARKDOWN'
} as const;
export type ContentFormat = typeof ContentFormat[keyof typeof ContentFormat];

