/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateApiKeyRequest { 
    /**
     * Human-readable name/label for the API key
     */
    name: string;
    /**
     * Optional duration in days until expiration. Omit for a non-expiring key.
     */
    expiresInDays?: number;
}

