/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentFormat } from './content-format.model';


export interface CreatePromptRequest { 
    /**
     * Human-readable prompt name
     */
    name: string;
    /**
     * Brief description of the prompt\'s purpose
     */
    description?: string;
    /**
     * Project/application this prompt belongs to
     */
    projectId: string;
    contentFormat?: ContentFormat;
    /**
     * The prompt content (5KB–50KB supported)
     */
    content: string;
    /**
     * User who created the prompt
     */
    author: string;
}
export namespace CreatePromptRequest {
}


