/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProjectRequest { 
    /**
     * Project name (unique)
     */
    name: string;
    /**
     * Brief description of the project
     */
    description?: string;
    /**
     * Tags for cross-project discovery
     */
    tags?: Array<string>;
}

