/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchResponse } from './search-response.model';


export interface DuplicateCheckResponse { 
    promptId?: string;
    hasDuplicates?: boolean;
    duplicates?: Array<SearchResponse>;
}

