/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Deployment environment for prompt promotion
 */
export const Environment = {
    Dev: 'DEV',
    Staging: 'STAGING',
    Production: 'PRODUCTION'
} as const;
export type Environment = typeof Environment[keyof typeof Environment];

