/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExportManifestFilters } from './export-manifest-filters.model';
import { ExportManifestSummary } from './export-manifest-summary.model';
import { PromptBundle } from './prompt-bundle.model';


export interface ExportManifest { 
    manifestVersion?: string;
    exportedAt?: string;
    exportedBy?: string;
    filters?: ExportManifestFilters;
    cursor?: string;
    prompts?: Array<PromptBundle>;
    summary?: ExportManifestSummary;
    checksum?: string;
}

