/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Severity } from './severity.model';
import { FindingType } from './finding-type.model';


export interface FindingResponse { 
    type?: FindingType;
    severity?: Severity;
    title?: string;
    description?: string;
    /**
     * Suggested fix
     */
    remediation?: string;
}
export namespace FindingResponse {
}


