/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Category of vulnerability finding
 */
export const FindingType = {
    PhiExposure: 'phi_exposure',
    InjectionRisk: 'injection_risk',
    MissingGuardrail: 'missing_guardrail',
    HallucinationProne: 'hallucination_prone',
    WeakToolCalling: 'weak_tool_calling'
} as const;
export type FindingType = typeof FindingType[keyof typeof FindingType];

