/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateFromIdeaResponse { 
    /**
     * The full prompt content generated by the LLM from the idea
     */
    generatedContent?: string;
    /**
     * A suggested title for the prompt
     */
    title?: string;
    /**
     * Explanation of the generated prompt structure and approach
     */
    summary?: string;
}

