/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateFromIdeaRequest { 
    /**
     * A short natural-language description of the prompt the user wants to create
     */
    idea: string;
    /**
     * Optional project context to ground the generation
     */
    projectId?: string;
}

