/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImprovementResponse { 
    promptId?: string;
    originalContent?: string;
    improvedContent?: string;
    /**
     * Explanation of what was improved
     */
    summary?: string;
}

