/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationResponse { 
    id?: string;
    userId?: string;
    projectId?: string;
    /**
     * Event type key (e.g., prompt.created, workflow.approved, scan.completed)
     */
    type?: string;
    /**
     * Human-readable notification title
     */
    title?: string;
    /**
     * Human-readable notification message
     */
    message?: string;
    /**
     * Material icon name for UI rendering
     */
    icon?: string;
    /**
     * Raw event payload for deep-linking or contextual display
     */
    payload?: { [key: string]: any; };
    /**
     * Whether the notification has been read
     */
    read?: boolean;
    createdAt?: string;
}

