/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationCountResponse { 
    /**
     * Number of unread notifications for the user in the project
     */
    unread?: number;
}

