/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationEventTypeInfo } from './notification-event-type-info.model';


export interface NotificationPreferenceResponse { 
    userId?: string;
    projectId?: string;
    /**
     * Event type keys that the user has muted
     */
    mutedEvents?: Array<string>;
    /**
     * Whether in-app notifications are enabled
     */
    inAppEnabled?: boolean;
    /**
     * Whether email notifications are enabled
     */
    emailEnabled?: boolean;
    /**
     * All available notification event types for the UI toggle grid
     */
    availableEvents?: Array<NotificationEventTypeInfo>;
}

