/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metadata for a notification event type used in the UI toggle grid
 */
export interface NotificationEventTypeInfo { 
    /**
     * Event type key (e.g., prompt.created, workflow.approved)
     */
    key?: string;
    /**
     * Human-readable display title
     */
    title?: string;
    /**
     * Material icon name for UI rendering
     */
    icon?: string;
    /**
     * Message template with {placeholder} variables
     */
    messageTemplate?: string;
}

