/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Organization-level role
 */
export const OrgRole = {
    OrgAdmin: 'ORG_ADMIN',
    OrgUser: 'ORG_USER'
} as const;
export type OrgRole = typeof OrgRole[keyof typeof OrgRole];

