/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationError } from './validation-error.model';


/**
 * RFC 9457 Problem Details for HTTP APIs — Standard error response format. Extension members (code, timestamp, traceId, errors) are permitted per §3.1.
 */
export interface ProblemDetails { 
    /**
     * URI reference identifying the problem type (§3.1.1)
     */
    type: string;
    /**
     * Short, human-readable summary of the problem type (§3.1.2)
     */
    title: string;
    /**
     * HTTP status code generated by the origin server for this occurrence (§3.1.3)
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence (§3.1.4)
     */
    detail?: string;
    /**
     * URI reference identifying the specific occurrence of the problem (§3.1.5)
     */
    instance?: string;
    /**
     * Machine-readable error code for frontend error message mapping
     */
    code?: string;
    /**
     * Timestamp when the error occurred (ISO 8601 format)
     */
    timestamp?: string;
    /**
     * Unique trace ID for debugging and log correlation
     */
    traceId?: string;
    /**
     * Field-level validation errors (for 400 Bad Request responses)
     */
    errors?: Array<ValidationError>;
}

