/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationError } from './validation-error.model';


/**
 * RFC 9457 Problem Details for HTTP APIs — Standard error response format
 */
export interface ProblemDetails { 
    /**
     * URI reference identifying the problem type (should resolve to human-readable documentation)
     */
    type: string;
    /**
     * Short, human-readable summary of the problem type
     */
    title: string;
    /**
     * HTTP status code generated by the origin server for this occurrence
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence of the problem
     */
    detail?: string;
    /**
     * URI reference identifying the specific occurrence of the problem
     */
    instance?: string;
    /**
     * Timestamp when the error occurred (ISO 8601 format)
     */
    timestamp?: string;
    /**
     * Unique trace ID for debugging and log correlation
     */
    traceId?: string;
    /**
     * Field-level validation errors (for 400 Bad Request responses)
     */
    errors?: Array<ValidationError>;
}

