/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectResponse { 
    id: string;
    name: string;
    description?: string;
    tags?: Array<string>;
    /**
     * Number of members in this project
     */
    memberCount?: number;
    /**
     * Number of prompts in this project
     */
    promptCount?: number;
    createdBy: string;
    createdAt: string;
    updatedAt?: string;
}

