/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectRole } from './project-role.model';


export interface ProjectMemberResponse { 
    userId: string;
    displayName: string;
    email: string;
    role: ProjectRole;
    addedBy?: string;
    addedAt?: string;
}
export namespace ProjectMemberResponse {
}


