/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Project-level RBAC role
 */
export const ProjectRole = {
    Viewer: 'VIEWER',
    Author: 'AUTHOR',
    Reviewer: 'REVIEWER',
    Approver: 'APPROVER',
    Admin: 'ADMIN'
} as const;
export type ProjectRole = typeof ProjectRole[keyof typeof ProjectRole];

