/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Project-level RBAC role
 */
export const ProjectRole = {
    Owner: 'OWNER',
    Editor: 'EDITOR',
    Viewer: 'VIEWER'
} as const;
export type ProjectRole = typeof ProjectRole[keyof typeof ProjectRole];

