/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationEventTypeInfo } from './notification-event-type-info.model';


export interface ProjectNotificationSettingsResponse { 
    projectId?: string;
    /**
     * Event type keys enabled for this project
     */
    enabledEvents?: Array<string>;
    /**
     * All available notification event types
     */
    availableEvents?: Array<NotificationEventTypeInfo>;
}

