/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromptSummaryResponse { 
    id?: string;
    name?: string;
    description?: string;
    projectId?: string;
    currentVersion?: number;
    activeEnvironment?: string;
    updatedAt?: string;
}

