/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PromptSummaryResponse { 
    id?: string;
    name?: string;
    description?: string;
    projectId?: string;
    status?: PromptSummaryResponse.StatusEnum;
    currentVersion?: number;
    updatedAt?: string;
}
export namespace PromptSummaryResponse {
    export type StatusEnum = 'DRAFT' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'DEPRECATED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        InReview: 'IN_REVIEW' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Deprecated: 'DEPRECATED' as StatusEnum,
    };
}

