/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle status of a prompt
 */
export const PromptStatus = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Deprecated: 'DEPRECATED'
} as const;
export type PromptStatus = typeof PromptStatus[keyof typeof PromptStatus];

