/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentFormat } from './content-format.model';


export interface PromptResponse { 
    /**
     * Unique prompt ID (MongoDB ObjectId)
     */
    id?: string;
    name?: string;
    description?: string;
    projectId?: string;
    status?: PromptResponse.StatusEnum;
    contentFormat?: ContentFormat;
    /**
     * Latest version number
     */
    currentVersion?: number;
    /**
     * Content of the latest version
     */
    latestContent?: string;
    tags?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
}
export namespace PromptResponse {
    export type StatusEnum = 'DRAFT' | 'IN_REVIEW' | 'APPROVED' | 'REJECTED' | 'DEPRECATED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        InReview: 'IN_REVIEW' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Deprecated: 'DEPRECATED' as StatusEnum,
    };
}


