/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentFormat } from './content-format.model';


export interface PromptResponse { 
    /**
     * Unique prompt ID (MongoDB ObjectId)
     */
    id?: string;
    name?: string;
    description?: string;
    projectId?: string;
    contentFormat?: ContentFormat;
    /**
     * Latest version number
     */
    currentVersion?: number;
    /**
     * Content of the latest version
     */
    latestContent?: string;
    tags?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
}
export namespace PromptResponse {
}


