/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindingResponse } from './finding-response.model';
import { ScanStatus } from './scan-status.model';


export interface ScanResponse { 
    id?: string;
    promptId?: string;
    promptVersion?: number;
    /**
     * Severity score (0.0 = safe, 10.0 = critical)
     */
    overallScore?: number;
    status?: ScanStatus;
    findings?: Array<FindingResponse>;
    llmProvider?: string;
    llmModel?: string;
    scannedAt?: string;
}
export namespace ScanResponse {
}


