/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubmitReviewRequest { 
    /**
     * ID of the prompt to submit for review
     */
    promptId: string;
    /**
     * Project the prompt belongs to (for filtering)
     */
    projectId?: string;
    /**
     * Version number of the prompt to review
     */
    promptVersion: number;
    /**
     * User requesting the review
     */
    requestedBy: string;
}

