/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubmitReviewRequest { 
    promptId: string;
    /**
     * Project the prompt belongs to (for filtering)
     */
    projectId?: string;
    promptVersion: number;
    requestedBy: string;
}

