/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Environment } from './environment.model';


export interface SubmitReviewRequest { 
    promptId: string;
    promptVersion: number;
    requestedBy: string;
    targetEnvironment: Environment;
}
export namespace SubmitReviewRequest {
}


