/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProjectNotificationSettingsRequest { 
    projectId: string;
    /**
     * Event type keys to enable for this project
     */
    enabledEvents?: Array<string>;
}

