/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgRole } from './org-role.model';
import { UserStatus } from './user-status.model';


export interface UserResponse { 
    /**
     * User\'s unique identifier
     */
    id: string;
    /**
     * User\'s email address
     */
    email: string;
    /**
     * User\'s display name
     */
    displayName: string;
    /**
     * URL to user\'s avatar image
     */
    avatarUrl?: string;
    orgRole: OrgRole;
    status: UserStatus;
    /**
     * Account creation timestamp
     */
    createdAt?: string;
}
export namespace UserResponse {
}


