/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPreferences { 
    /**
     * Master switch for in-app (bell icon) notifications
     */
    inAppEnabled: boolean;
    /**
     * Master switch for email notifications
     */
    emailEnabled: boolean;
    /**
     * List of event types the user has silenced
     */
    mutedEvents?: Array<string>;
}

