/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Field-level validation error details
 */
export interface ValidationError { 
    /**
     * Name of the field that failed validation
     */
    field: string;
    /**
     * Validation error message for this field
     */
    message: string;
    /**
     * The value that was rejected (may be null)
     */
    rejectedValue?: string;
    /**
     * Machine-readable error code for this field
     */
    code?: string;
}

