/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowStepResponse } from './workflow-step-response.model';
import { WorkflowStatus } from './workflow-status.model';


export interface WorkflowResponse { 
    id?: string;
    promptId?: string;
    promptVersion?: number;
    /**
     * Workflow type (e.g., approval)
     */
    type?: string;
    status?: WorkflowStatus;
    currentStep?: number;
    requestedBy?: string;
    steps?: Array<WorkflowStepResponse>;
    createdAt?: string;
    updatedAt?: string;
}
export namespace WorkflowResponse {
}


