/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current status of a workflow
 */
export const WorkflowStatus = {
    Pending: 'PENDING',
    InReview: 'IN_REVIEW',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Cancelled: 'CANCELLED'
} as const;
export type WorkflowStatus = typeof WorkflowStatus[keyof typeof WorkflowStatus];

