/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuditResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ExportAuditLogsRequestParams {
    resourceId?: string;
}

export interface GetAuditLogsRequestParams {
    resourceId?: string;
    userId?: string;
    action?: string;
}


export interface AuditServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Export audit logs
     * Exports audit trail for SOC2/HIPAA compliance.
     * @endpoint post /api/v1/audit-logs/export
* @param requestParameters
     */
    exportAuditLogs(requestParameters: ExportAuditLogsRequestParams, extraHttpRequestParams?: any): Observable<Array<AuditResponse>>;

    /**
     * Query audit logs
     * Returns immutable audit trail entries. Filter by resource ID, user ID, or action type. If no filter is provided, returns all entries. 
     * @endpoint get /api/v1/audit-logs
* @param requestParameters
     */
    getAuditLogs(requestParameters: GetAuditLogsRequestParams, extraHttpRequestParams?: any): Observable<Array<AuditResponse>>;

}
