/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthResponse } from '../model/models';
import { LoginRequest } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RefreshTokenRequest } from '../model/models';
import { RegisterRequest } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { UserPreferences } from '../model/models';
import { UserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ListUsersRequestParams {
    q?: string;
    limit?: number;
}

export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface RefreshTokenRequestParams {
    refreshTokenRequest: RefreshTokenRequest;
}

export interface RegisterRequestParams {
    registerRequest: RegisterRequest;
}

export interface UpdateCurrentUserRequestParams {
    updateUserRequest: UpdateUserRequest;
}

export interface UpdateUserPreferencesRequestParams {
    userPreferences: UserPreferences;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get current authenticated user
     * Returns the profile of the currently authenticated user from the JWT token.
     * @endpoint get /api/v1/auth/me
*/
    getCurrentUser(extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Get user preferences
     * Returns the notification and platform preferences for the authenticated user.
     * @endpoint get /api/v1/auth/me/preferences
*/
    getUserPreferences(extraHttpRequestParams?: any): Observable<UserPreferences>;

    /**
     * Search users
     * Returns a list of users matching the search query. Used for project member picker (autocomplete). Requires authentication. 
     * @endpoint get /api/v1/users
* @param requestParameters
     */
    listUsers(requestParameters: ListUsersRequestParams, extraHttpRequestParams?: any): Observable<Array<UserResponse>>;

    /**
     * Login with email and password
     * Authenticates a user with email/password and returns JWT tokens. Disabled when auth provider is set to OIDC. 
     * @endpoint post /api/v1/auth/login
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * Refresh access token
     * Exchanges a valid refresh token for a new access token pair.
     * @endpoint post /api/v1/auth/refresh
* @param requestParameters
     */
    refreshToken(requestParameters: RefreshTokenRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * Register a new user
     * Creates a new user account with the LOCAL auth provider. The first registered user automatically becomes ORG_ADMIN. Disabled when auth provider is set to OIDC. 
     * @endpoint post /api/v1/auth/register
* @param requestParameters
     */
    register(requestParameters: RegisterRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * Update current user profile
     * Updates the display name and/or avatar of the authenticated user.
     * @endpoint patch /api/v1/auth/me
* @param requestParameters
     */
    updateCurrentUser(requestParameters: UpdateCurrentUserRequestParams, extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Update user preferences
     * Updates notification settings and other preferences.
     * @endpoint patch /api/v1/auth/me/preferences
* @param requestParameters
     */
    updateUserPreferences(requestParameters: UpdateUserPreferencesRequestParams, extraHttpRequestParams?: any): Observable<UserPreferences>;

}
