/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeliveryResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeliverPromptRequestParams {
    appId: string;
    usecase?: string;
    agent?: string;
}


export interface DeliveryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Deliver prompt to AI agent
     * Low-latency endpoint for AI agents to fetch the latest active prompt by application ID and optional use case / agent identifiers. 
     * @endpoint get /api/v1/deliver
* @param requestParameters
     */
    deliverPrompt(requestParameters: DeliverPromptRequestParams, extraHttpRequestParams?: any): Observable<DeliveryResponse>;

}
