/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplyImprovementRequest } from '../model/models';
import { ImprovementResponse } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApplyImprovementRequestParams {
    promptId: string;
    applyImprovementRequest: ApplyImprovementRequest;
}

export interface ImprovePromptRequestParams {
    promptId: string;
}


export interface ImproverServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Apply an improvement
     * Accepts the improved content and creates a new prompt version.
     * @endpoint post /api/v1/prompts/{promptId}/apply-improvement
* @param requestParameters
     */
    applyImprovement(requestParameters: ApplyImprovementRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Generate AI improvement suggestions
     * Uses LLM to analyze the prompt and generate an improved version with explanation.
     * @endpoint post /api/v1/prompts/{promptId}/improve
* @param requestParameters
     */
    improvePrompt(requestParameters: ImprovePromptRequestParams, extraHttpRequestParams?: any): Observable<ImprovementResponse>;

}
