/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { NotificationCountResponse } from '../model/models';
import { NotificationListResponse } from '../model/models';
import { NotificationPreferenceResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ProjectNotificationSettingsResponse } from '../model/models';
import { UpdateNotificationPreferenceRequest } from '../model/models';
import { UpdateProjectNotificationSettingsRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ClearAllNotificationsRequestParams {
    projectId: string;
}

export interface DismissNotificationRequestParams {
    id: string;
}

export interface GetNotificationPreferencesRequestParams {
    projectId: string;
}

export interface GetProjectNotificationSettingsRequestParams {
    projectId: string;
}

export interface GetUnreadNotificationCountRequestParams {
    projectId: string;
}

export interface ListNotificationsRequestParams {
    projectId: string;
    unreadOnly?: boolean;
    before?: string;
    limit?: number;
}

export interface MarkAllNotificationsReadRequestParams {
    projectId: string;
}

export interface MarkNotificationAsReadRequestParams {
    id: string;
}

export interface UpdateNotificationPreferencesRequestParams {
    updateNotificationPreferenceRequest: UpdateNotificationPreferenceRequest;
}

export interface UpdateProjectNotificationSettingsRequestParams {
    updateProjectNotificationSettingsRequest: UpdateProjectNotificationSettingsRequest;
}


export interface NotificationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Clear all notifications
     * Deletes all notifications for the authenticated user in the specified project. 
     * @endpoint delete /api/v1/notifications
* @param requestParameters
     */
    clearAllNotifications(requestParameters: ClearAllNotificationsRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Dismiss a notification
     * Permanently deletes a single notification for the authenticated user.
     * @endpoint delete /api/v1/notifications/{id}/read
* @param requestParameters
     */
    dismissNotification(requestParameters: DismissNotificationRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get notification preferences
     * Returns the current user\&#39;s notification preferences for a project.
     * @endpoint get /api/v1/notifications/preferences
* @param requestParameters
     */
    getNotificationPreferences(requestParameters: GetNotificationPreferencesRequestParams, extraHttpRequestParams?: any): Observable<NotificationPreferenceResponse>;

    /**
     * Get project notification settings
     * Returns project-level notification settings (which event types are enabled).
     * @endpoint get /api/v1/notifications/project-settings
* @param requestParameters
     */
    getProjectNotificationSettings(requestParameters: GetProjectNotificationSettingsRequestParams, extraHttpRequestParams?: any): Observable<ProjectNotificationSettingsResponse>;

    /**
     * Get unread notification count
     * Returns the number of unread notifications for the bell badge.
     * @endpoint get /api/v1/notifications/count
* @param requestParameters
     */
    getUnreadNotificationCount(requestParameters: GetUnreadNotificationCountRequestParams, extraHttpRequestParams?: any): Observable<NotificationCountResponse>;

    /**
     * List notifications
     * Cursor-based notification list for the authenticated user. Returns notifications for the specified project, ordered by creation time descending. 
     * @endpoint get /api/v1/notifications
* @param requestParameters
     */
    listNotifications(requestParameters: ListNotificationsRequestParams, extraHttpRequestParams?: any): Observable<NotificationListResponse>;

    /**
     * Mark all notifications as read
     * Marks all unread notifications as read for the authenticated user in the specified project. 
     * @endpoint post /api/v1/notifications/mark-all-read
* @param requestParameters
     */
    markAllNotificationsRead(requestParameters: MarkAllNotificationsReadRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Mark a notification as read
     * Marks a single notification as read for the authenticated user.
     * @endpoint patch /api/v1/notifications/{id}/read
* @param requestParameters
     */
    markNotificationAsRead(requestParameters: MarkNotificationAsReadRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update notification preferences
     * Updates the current user\&#39;s notification preferences for a project.
     * @endpoint put /api/v1/notifications/preferences
* @param requestParameters
     */
    updateNotificationPreferences(requestParameters: UpdateNotificationPreferencesRequestParams, extraHttpRequestParams?: any): Observable<NotificationPreferenceResponse>;

    /**
     * Update project notification settings
     * Updates project-level notification settings (admin-level).
     * @endpoint put /api/v1/notifications/project-settings
* @param requestParameters
     */
    updateProjectNotificationSettings(requestParameters: UpdateProjectNotificationSettingsRequestParams, extraHttpRequestParams?: any): Observable<ProjectNotificationSettingsResponse>;

}
