/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddMemberRequest } from '../model/models';
import { CreateProjectRequest } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ProjectMemberResponse } from '../model/models';
import { ProjectResponse } from '../model/models';
import { UpdateMemberRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddProjectMemberRequestParams {
    projectId: string;
    addMemberRequest: AddMemberRequest;
}

export interface CreateProjectRequestParams {
    createProjectRequest: CreateProjectRequest;
}

export interface GetProjectRequestParams {
    id: string;
}

export interface ListProjectMembersRequestParams {
    projectId: string;
}

export interface RemoveProjectMemberRequestParams {
    projectId: string;
    userId: string;
}

export interface UpdateProjectMemberRequestParams {
    projectId: string;
    userId: string;
    updateMemberRequest: UpdateMemberRequest;
}


export interface ProjectsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a member to a project
     * 
     * @endpoint post /api/v1/projects/{projectId}/members
* @param requestParameters
     */
    addProjectMember(requestParameters: AddProjectMemberRequestParams, extraHttpRequestParams?: any): Observable<ProjectMemberResponse>;

    /**
     * Create a new project
     * Creates a new project. The creator automatically becomes ADMIN.
     * @endpoint post /api/v1/projects
* @param requestParameters
     */
    createProject(requestParameters: CreateProjectRequestParams, extraHttpRequestParams?: any): Observable<ProjectResponse>;

    /**
     * Get project by ID
     * 
     * @endpoint get /api/v1/projects/{id}
* @param requestParameters
     */
    getProject(requestParameters: GetProjectRequestParams, extraHttpRequestParams?: any): Observable<ProjectResponse>;

    /**
     * List project members
     * 
     * @endpoint get /api/v1/projects/{projectId}/members
* @param requestParameters
     */
    listProjectMembers(requestParameters: ListProjectMembersRequestParams, extraHttpRequestParams?: any): Observable<Array<ProjectMemberResponse>>;

    /**
     * List all projects
     * Returns all projects the current user has access to.
     * @endpoint get /api/v1/projects
*/
    listProjects(extraHttpRequestParams?: any): Observable<Array<ProjectResponse>>;

    /**
     * Remove a member from a project
     * 
     * @endpoint delete /api/v1/projects/{projectId}/members/{userId}
* @param requestParameters
     */
    removeProjectMember(requestParameters: RemoveProjectMemberRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a project member\&#39;s role
     * 
     * @endpoint put /api/v1/projects/{projectId}/members/{userId}
* @param requestParameters
     */
    updateProjectMember(requestParameters: UpdateProjectMemberRequestParams, extraHttpRequestParams?: any): Observable<ProjectMemberResponse>;

}
