/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePromptRequest } from '../model/models';
import { GenerateFromIdeaRequest } from '../model/models';
import { GenerateFromIdeaResponse } from '../model/models';
import { ProblemDetails } from '../model/models';
import { PromptResponse } from '../model/models';
import { PromptSummaryResponse } from '../model/models';
import { UpdatePromptRequest } from '../model/models';
import { VersionResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreatePromptRequestParams {
    createPromptRequest: CreatePromptRequest;
}

export interface DeletePromptRequestParams {
    id: string;
}

export interface GenerateFromIdeaRequestParams {
    generateFromIdeaRequest: GenerateFromIdeaRequest;
}

export interface GetPromptRequestParams {
    id: string;
}

export interface GetSpecificVersionRequestParams {
    id: string;
    versionNumber: number;
}

export interface GetVersionHistoryRequestParams {
    id: string;
}

export interface ListPromptsRequestParams {
    projectId?: string;
    page?: number;
    size?: number;
    sort?: string;
}

export interface RollbackPromptRequestParams {
    id: string;
    targetVersion: number;
    author?: string;
}

export interface UpdatePromptRequestParams {
    id: string;
    updatePromptRequest: UpdatePromptRequest;
}


export interface PromptsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new prompt
     * Creates a new prompt with version 1. Emits &#x60;PromptCreated&#x60; event which triggers auto-scan and embedding generation.
     * @endpoint post /api/v1/prompts
* @param requestParameters
     */
    createPrompt(requestParameters: CreatePromptRequestParams, extraHttpRequestParams?: any): Observable<PromptResponse>;

    /**
     * Delete a prompt
     * Permanently deletes a prompt and all its versions.
     * @endpoint delete /api/v1/prompts/{id}
* @param requestParameters
     */
    deletePrompt(requestParameters: DeletePromptRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Generate a prompt from a natural-language idea
     * Uses a dedicated LLM system prompt to transform a short idea description into a fully-structured AI prompt. Unlike the improve endpoint, this does not require an existing prompt — it creates content from scratch. 
     * @endpoint post /api/v1/prompts/generate
* @param requestParameters
     */
    generateFromIdea(requestParameters: GenerateFromIdeaRequestParams, extraHttpRequestParams?: any): Observable<GenerateFromIdeaResponse>;

    /**
     * Get prompt details
     * Returns full prompt details including latest content, tags, and timestamps.
     * @endpoint get /api/v1/prompts/{id}
* @param requestParameters
     */
    getPrompt(requestParameters: GetPromptRequestParams, extraHttpRequestParams?: any): Observable<PromptResponse>;

    /**
     * Get a specific version
     * Returns the content and metadata of a specific prompt version.
     * @endpoint get /api/v1/prompts/{id}/versions/{versionNumber}
* @param requestParameters
     */
    getSpecificVersion(requestParameters: GetSpecificVersionRequestParams, extraHttpRequestParams?: any): Observable<VersionResponse>;

    /**
     * Get version history
     * Returns all versions of a prompt, ordered by version number.
     * @endpoint get /api/v1/prompts/{id}/versions
* @param requestParameters
     */
    getVersionHistory(requestParameters: GetVersionHistoryRequestParams, extraHttpRequestParams?: any): Observable<Array<VersionResponse>>;

    /**
     * List prompts (paginated)
     * Returns a paginated, streaming list of prompt summaries. Optionally filter by project ID.
     * @endpoint get /api/v1/prompts
* @param requestParameters
     */
    listPrompts(requestParameters: ListPromptsRequestParams, extraHttpRequestParams?: any): Observable<Array<PromptSummaryResponse>>;

    /**
     * Rollback to a previous version
     * Restores prompt content from a previous version and creates a new version with that content. Emits &#x60;PromptRolledBack&#x60; event.
     * @endpoint post /api/v1/prompts/{id}/rollback/{targetVersion}
* @param requestParameters
     */
    rollbackPrompt(requestParameters: RollbackPromptRequestParams, extraHttpRequestParams?: any): Observable<PromptResponse>;

    /**
     * Update prompt content
     * Creates a new version of the prompt with updated content. Emits &#x60;PromptUpdated&#x60; event which triggers auto-scan and embedding refresh.
     * @endpoint put /api/v1/prompts/{id}
* @param requestParameters
     */
    updatePrompt(requestParameters: UpdatePromptRequestParams, extraHttpRequestParams?: any): Observable<PromptResponse>;

}
