/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetails } from '../model/models';
import { ScanResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetAllScansRequestParams {
    projectId?: string;
}

export interface GetLatestScanResultRequestParams {
    promptId: string;
}

export interface TriggerScanRequestParams {
    promptId: string;
}


export interface ScannerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List all scan results
     * Returns all scan results across all prompts. Optionally filter by project ID.
     * @endpoint get /api/v1/scans
* @param requestParameters
     */
    getAllScans(requestParameters: GetAllScansRequestParams, extraHttpRequestParams?: any): Observable<Array<ScanResponse>>;

    /**
     * Get latest scan result
     * Returns the most recent scan result for a prompt.
     * @endpoint get /api/v1/prompts/{promptId}/scan-results
* @param requestParameters
     */
    getLatestScanResult(requestParameters: GetLatestScanResultRequestParams, extraHttpRequestParams?: any): Observable<ScanResponse>;

    /**
     * Trigger a vulnerability scan
     * Runs an LLM-powered vulnerability analysis on the prompt\&#39;s latest version.
     * @endpoint post /api/v1/prompts/{promptId}/scan
* @param requestParameters
     */
    triggerScan(requestParameters: TriggerScanRequestParams, extraHttpRequestParams?: any): Observable<ScanResponse>;

}
