/**
 * Promptly API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DuplicateCheckResponse } from '../model/models';
import { SearchResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CheckDuplicatesRequestParams {
    promptId: string;
}

export interface FindSimilarPromptsRequestParams {
    promptId: string;
}

export interface SearchPromptsRequestParams {
    q: string;
}


export interface SearchServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Check for duplicate prompts
     * Identifies potential duplicates based on content similarity (threshold ≥ 0.9).
     * @endpoint post /api/v1/prompts/{promptId}/check-duplicates
* @param requestParameters
     */
    checkDuplicates(requestParameters: CheckDuplicatesRequestParams, extraHttpRequestParams?: any): Observable<DuplicateCheckResponse>;

    /**
     * Find similar prompts
     * Finds prompts with similar content using vector similarity.
     * @endpoint get /api/v1/prompts/{promptId}/similar
* @param requestParameters
     */
    findSimilarPrompts(requestParameters: FindSimilarPromptsRequestParams, extraHttpRequestParams?: any): Observable<Array<SearchResponse>>;

    /**
     * Semantic search for prompts
     * Uses embedding-based vector search to find prompts similar to the query text.
     * @endpoint get /api/v1/search
* @param requestParameters
     */
    searchPrompts(requestParameters: SearchPromptsRequestParams, extraHttpRequestParams?: any): Observable<Array<SearchResponse>>;

}
