/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeliveryResponse,
  ProblemDetails,
  ProjectResponse,
  PromptResponse,
  PromptSummaryResponse,
  SearchResponse,
  VersionResponse,
} from '../models/index';
import {
    DeliveryResponseFromJSON,
    DeliveryResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ProjectResponseFromJSON,
    ProjectResponseToJSON,
    PromptResponseFromJSON,
    PromptResponseToJSON,
    PromptSummaryResponseFromJSON,
    PromptSummaryResponseToJSON,
    SearchResponseFromJSON,
    SearchResponseToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index';

export interface DeliverPromptRequest {
    appId: string;
    usecase?: string;
    agent?: string;
}

export interface GetProjectRequest {
    id: string;
}

export interface GetPromptRequest {
    id: string;
}

export interface GetSpecificVersionRequest {
    id: string;
    versionNumber: number;
}

export interface GetVersionHistoryRequest {
    id: string;
}

export interface ListPromptsRequest {
    projectId?: string;
}

export interface SearchPromptsRequest {
    q: string;
}

/**
 * 
 */
export class PromptlyQueryApi extends runtime.BaseAPI {

    /**
     * Creates request options for deliverPrompt without sending the request
     */
    async deliverPromptRequestOpts(requestParameters: DeliverPromptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling deliverPrompt().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['appId'] != null) {
            queryParameters['appId'] = requestParameters['appId'];
        }

        if (requestParameters['usecase'] != null) {
            queryParameters['usecase'] = requestParameters['usecase'];
        }

        if (requestParameters['agent'] != null) {
            queryParameters['agent'] = requestParameters['agent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/deliver`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Low-latency endpoint for AI agents to fetch the latest active prompt by application ID and optional use case / agent identifiers. 
     * Deliver prompt to AI agent
     */
    async deliverPromptRaw(requestParameters: DeliverPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeliveryResponse>> {
        const requestOptions = await this.deliverPromptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Low-latency endpoint for AI agents to fetch the latest active prompt by application ID and optional use case / agent identifiers. 
     * Deliver prompt to AI agent
     */
    async deliverPrompt(requestParameters: DeliverPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeliveryResponse> {
        const response = await this.deliverPromptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProject without sending the request
     */
    async getProjectRequestOpts(requestParameters: GetProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/projects/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get project by ID
     */
    async getProjectRaw(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        const requestOptions = await this.getProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Get project by ID
     */
    async getProject(requestParameters: GetProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.getProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPrompt without sending the request
     */
    async getPromptRequestOpts(requestParameters: GetPromptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPrompt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prompts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns full prompt details including latest content, tags, and timestamps.
     * Get prompt details
     */
    async getPromptRaw(requestParameters: GetPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromptResponse>> {
        const requestOptions = await this.getPromptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromptResponseFromJSON(jsonValue));
    }

    /**
     * Returns full prompt details including latest content, tags, and timestamps.
     * Get prompt details
     */
    async getPrompt(requestParameters: GetPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromptResponse> {
        const response = await this.getPromptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSpecificVersion without sending the request
     */
    async getSpecificVersionRequestOpts(requestParameters: GetSpecificVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSpecificVersion().'
            );
        }

        if (requestParameters['versionNumber'] == null) {
            throw new runtime.RequiredError(
                'versionNumber',
                'Required parameter "versionNumber" was null or undefined when calling getSpecificVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prompts/{id}/versions/{versionNumber}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"versionNumber"}}`, encodeURIComponent(String(requestParameters['versionNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the content and metadata of a specific prompt version.
     * Get a specific version
     */
    async getSpecificVersionRaw(requestParameters: GetSpecificVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionResponse>> {
        const requestOptions = await this.getSpecificVersionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionResponseFromJSON(jsonValue));
    }

    /**
     * Returns the content and metadata of a specific prompt version.
     * Get a specific version
     */
    async getSpecificVersion(requestParameters: GetSpecificVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionResponse> {
        const response = await this.getSpecificVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVersionHistory without sending the request
     */
    async getVersionHistoryRequestOpts(requestParameters: GetVersionHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVersionHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prompts/{id}/versions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all versions of a prompt, ordered by version number.
     * Get version history
     */
    async getVersionHistoryRaw(requestParameters: GetVersionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VersionResponse>>> {
        const requestOptions = await this.getVersionHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VersionResponseFromJSON));
    }

    /**
     * Returns all versions of a prompt, ordered by version number.
     * Get version history
     */
    async getVersionHistory(requestParameters: GetVersionHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VersionResponse>> {
        const response = await this.getVersionHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProjects without sending the request
     */
    async listProjectsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all projects the current user has access to.
     * List all projects
     */
    async listProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectResponse>>> {
        const requestOptions = await this.listProjectsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectResponseFromJSON));
    }

    /**
     * Returns all projects the current user has access to.
     * List all projects
     */
    async listProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectResponse>> {
        const response = await this.listProjectsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPrompts without sending the request
     */
    async listPromptsRequestOpts(requestParameters: ListPromptsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['projectId'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/prompts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of prompt summaries. Optionally filter by project ID.
     * List all prompts
     */
    async listPromptsRaw(requestParameters: ListPromptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PromptSummaryResponse>>> {
        const requestOptions = await this.listPromptsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PromptSummaryResponseFromJSON));
    }

    /**
     * Returns a list of prompt summaries. Optionally filter by project ID.
     * List all prompts
     */
    async listPrompts(requestParameters: ListPromptsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PromptSummaryResponse>> {
        const response = await this.listPromptsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchPrompts without sending the request
     */
    async searchPromptsRequestOpts(requestParameters: SearchPromptsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchPrompts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Uses embedding-based vector search to find prompts similar to the query text.
     * Semantic search for prompts
     */
    async searchPromptsRaw(requestParameters: SearchPromptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SearchResponse>>> {
        const requestOptions = await this.searchPromptsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SearchResponseFromJSON));
    }

    /**
     * Uses embedding-based vector search to find prompts similar to the query text.
     * Semantic search for prompts
     */
    async searchPrompts(requestParameters: SearchPromptsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SearchResponse>> {
        const response = await this.searchPromptsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
