/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.AuthResponse;
import com.promptly.infrastructure.in.web.dto.LoginRequest;
import org.springframework.lang.Nullable;
import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import com.promptly.infrastructure.in.web.dto.RefreshTokenRequest;
import com.promptly.infrastructure.in.web.dto.RegisterRequest;
import com.promptly.infrastructure.in.web.dto.UserResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-23T20:26:14.636453-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Auth", description = "Authentication — registration, login, token management (LOCAL mode)")
public interface AuthApi {

    String PATH_GET_CURRENT_USER = "/api/v1/auth/me";
    /**
     * GET /api/v1/auth/me : Get current authenticated user
     * Returns the profile of the currently authenticated user from the JWT token.
     *
     * @return Current user profile (status code 200)
     *         or Authentication is required and has failed or has not been provided (status code 401)
     */
    @Operation(
        operationId = "getCurrentUser",
        summary = "Get current authenticated user",
        description = "Returns the profile of the currently authenticated user from the JWT token.",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Current user profile", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Authentication is required and has failed or has not been provided", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_GET_CURRENT_USER,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<UserResponse>> getCurrentUser(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_USERS = "/api/v1/users";
    /**
     * GET /api/v1/users : Search users
     * Returns a list of users matching the search query. Used for project member picker (autocomplete). Requires authentication. 
     *
     * @param q Search query (matches email or display name) (optional)
     * @param limit Maximum number of results (optional, default to 20)
     * @return List of matching users (status code 200)
     *         or Authentication is required and has failed or has not been provided (status code 401)
     */
    @Operation(
        operationId = "listUsers",
        summary = "Search users",
        description = "Returns a list of users matching the search query. Used for project member picker (autocomplete). Requires authentication. ",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of matching users", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UserResponse.class))),
                @Content(mediaType = "application/problem+json", array = @ArraySchema(schema = @Schema(implementation = UserResponse.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Authentication is required and has failed or has not been provided", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_LIST_USERS,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<Flux<UserResponse>>> listUsers(
        @Parameter(name = "q", description = "Search query (matches email or display name)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "q", required = false) @Nullable String q,
        @Max(value = 100) @Parameter(name = "limit", description = "Maximum number of results", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LOGIN = "/api/v1/auth/login";
    /**
     * POST /api/v1/auth/login : Login with email and password
     * Authenticates a user with email/password and returns JWT tokens. Disabled when auth provider is set to OIDC. 
     *
     * @param loginRequest  (required)
     * @return Login successful (status code 200)
     *         or Authentication is required and has failed or has not been provided (status code 401)
     */
    @Operation(
        operationId = "login",
        summary = "Login with email and password",
        description = "Authenticates a user with email/password and returns JWT tokens. Disabled when auth provider is set to OIDC. ",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Login successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Authentication is required and has failed or has not been provided", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_LOGIN,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<AuthResponse>> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody Mono<LoginRequest> loginRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_REFRESH_TOKEN = "/api/v1/auth/refresh";
    /**
     * POST /api/v1/auth/refresh : Refresh access token
     * Exchanges a valid refresh token for a new access token pair.
     *
     * @param refreshTokenRequest  (required)
     * @return Token refreshed successfully (status code 200)
     *         or Authentication is required and has failed or has not been provided (status code 401)
     */
    @Operation(
        operationId = "refreshToken",
        summary = "Refresh access token",
        description = "Exchanges a valid refresh token for a new access token pair.",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Token refreshed successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Authentication is required and has failed or has not been provided", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_REFRESH_TOKEN,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<AuthResponse>> refreshToken(
        @Parameter(name = "RefreshTokenRequest", description = "", required = true) @Valid @RequestBody Mono<RefreshTokenRequest> refreshTokenRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_REGISTER = "/api/v1/auth/register";
    /**
     * POST /api/v1/auth/register : Register a new user
     * Creates a new user account with the LOCAL auth provider. The first registered user automatically becomes ORG_ADMIN. Disabled when auth provider is set to OIDC. 
     *
     * @param registerRequest  (required)
     * @return User registered successfully (status code 201)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     *         or The request conflicts with the current state of the resource (status code 409)
     */
    @Operation(
        operationId = "register",
        summary = "Register a new user",
        description = "Creates a new user account with the LOCAL auth provider. The first registered user automatically becomes ORG_ADMIN. Disabled when auth provider is set to OIDC. ",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User registered successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "409", description = "The request conflicts with the current state of the resource", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_REGISTER,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<AuthResponse>> register(
        @Parameter(name = "RegisterRequest", description = "", required = true) @Valid @RequestBody Mono<RegisterRequest> registerRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
