/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.DeliveryResponse;
import org.springframework.lang.Nullable;
import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-25T18:29:22.472644400-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Delivery", description = "Runtime Delivery — low-latency prompt serving for AI agents")
public interface DeliveryApi {

    String PATH_DELIVER_PROMPT = "/api/v1/deliver";
    /**
     * GET /api/v1/deliver : Deliver prompt to AI agent
     * Low-latency endpoint for AI agents to fetch the latest active prompt by application ID and optional use case / agent identifiers. 
     *
     * @param appId Application/project identifier (required)
     * @param usecase Use case filter (optional)
     * @param agent Agent identifier filter (optional)
     * @return Prompt content delivered (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "deliverPrompt",
        summary = "Deliver prompt to AI agent",
        description = "Low-latency endpoint for AI agents to fetch the latest active prompt by application ID and optional use case / agent identifiers. ",
        tags = { "Delivery" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Prompt content delivered", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeliveryResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = DeliveryResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DeliveryApi.PATH_DELIVER_PROMPT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<DeliveryResponse>> deliverPrompt(
        @NotNull @Parameter(name = "appId", description = "Application/project identifier", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "appId", required = true) String appId,
        @Parameter(name = "usecase", description = "Use case filter", in = ParameterIn.QUERY) @Valid @RequestParam(value = "usecase", required = false) @Nullable String usecase,
        @Parameter(name = "agent", description = "Agent identifier filter", in = ParameterIn.QUERY) @Valid @RequestParam(value = "agent", required = false) @Nullable String agent,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
