/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.ApplyImprovementRequest;
import com.promptly.infrastructure.in.web.dto.ImprovementResponse;
import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-28T16:27:22.798239400-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Improver", description = "Quality Improver — AI-assisted prompt refinement")
public interface ImproverApi {

    String PATH_APPLY_IMPROVEMENT = "/api/v1/prompts/{promptId}/apply-improvement";
    /**
     * POST /api/v1/prompts/{promptId}/apply-improvement : Apply an improvement
     * Accepts the improved content and creates a new prompt version.
     *
     * @param promptId Prompt identifier (required)
     * @param applyImprovementRequest  (required)
     * @return Improvement applied (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "applyImprovement",
        summary = "Apply an improvement",
        description = "Accepts the improved content and creates a new prompt version.",
        tags = { "Improver" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Improvement applied"),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ImproverApi.PATH_APPLY_IMPROVEMENT,
        produces = { "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<Void>> applyImprovement(
        @Parameter(name = "promptId", description = "Prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("promptId") String promptId,
        @Parameter(name = "ApplyImprovementRequest", description = "", required = true) @Valid @RequestBody Mono<ApplyImprovementRequest> applyImprovementRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_IMPROVE_PROMPT = "/api/v1/prompts/{promptId}/improve";
    /**
     * POST /api/v1/prompts/{promptId}/improve : Generate AI improvement suggestions
     * Uses LLM to analyze the prompt and generate an improved version with explanation.
     *
     * @param promptId Prompt identifier (required)
     * @return Improvement suggestion (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "improvePrompt",
        summary = "Generate AI improvement suggestions",
        description = "Uses LLM to analyze the prompt and generate an improved version with explanation.",
        tags = { "Improver" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Improvement suggestion", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImprovementResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ImprovementResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ImproverApi.PATH_IMPROVE_PROMPT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ImprovementResponse>> improvePrompt(
        @Parameter(name = "promptId", description = "Prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("promptId") String promptId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
