/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.AddMemberRequest;
import com.promptly.infrastructure.in.web.dto.CreateProjectRequest;
import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import com.promptly.infrastructure.in.web.dto.ProjectMemberResponse;
import com.promptly.infrastructure.in.web.dto.ProjectResponse;
import com.promptly.infrastructure.in.web.dto.UpdateMemberRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-25T18:29:22.472644400-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Projects", description = "Projects — RBAC boundaries, team management")
public interface ProjectsApi {

    String PATH_ADD_PROJECT_MEMBER = "/api/v1/projects/{projectId}/members";
    /**
     * POST /api/v1/projects/{projectId}/members : Add a member to a project
     *
     * @param projectId  (required)
     * @param addMemberRequest  (required)
     * @return Member added (status code 201)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     *         or The request conflicts with the current state of the resource (status code 409)
     */
    @Operation(
        operationId = "addProjectMember",
        summary = "Add a member to a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Member added", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectMemberResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProjectMemberResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "409", description = "The request conflicts with the current state of the resource", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProjectsApi.PATH_ADD_PROJECT_MEMBER,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<ProjectMemberResponse>> addProjectMember(
        @Parameter(name = "projectId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "AddMemberRequest", description = "", required = true) @Valid @RequestBody Mono<AddMemberRequest> addMemberRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_CREATE_PROJECT = "/api/v1/projects";
    /**
     * POST /api/v1/projects : Create a new project
     * Creates a new project. The creator automatically becomes ADMIN.
     *
     * @param createProjectRequest  (required)
     * @return Project created (status code 201)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     *         or The request conflicts with the current state of the resource (status code 409)
     */
    @Operation(
        operationId = "createProject",
        summary = "Create a new project",
        description = "Creates a new project. The creator automatically becomes ADMIN.",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Project created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProjectResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "409", description = "The request conflicts with the current state of the resource", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ProjectsApi.PATH_CREATE_PROJECT,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<ProjectResponse>> createProject(
        @Parameter(name = "CreateProjectRequest", description = "", required = true) @Valid @RequestBody Mono<CreateProjectRequest> createProjectRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_PROJECT = "/api/v1/projects/{id}";
    /**
     * GET /api/v1/projects/{id} : Get project by ID
     *
     * @param id  (required)
     * @return Project details (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "getProject",
        summary = "Get project by ID",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Project details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProjectResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectsApi.PATH_GET_PROJECT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ProjectResponse>> getProject(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_PROJECT_MEMBERS = "/api/v1/projects/{projectId}/members";
    /**
     * GET /api/v1/projects/{projectId}/members : List project members
     *
     * @param projectId  (required)
     * @return List of project members (status code 200)
     */
    @Operation(
        operationId = "listProjectMembers",
        summary = "List project members",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of project members", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectMemberResponse.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectsApi.PATH_LIST_PROJECT_MEMBERS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<Flux<ProjectMemberResponse>>> listProjectMembers(
        @Parameter(name = "projectId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_PROJECTS = "/api/v1/projects";
    /**
     * GET /api/v1/projects : List all projects
     * Returns all projects the current user has access to.
     *
     * @return List of projects (status code 200)
     */
    @Operation(
        operationId = "listProjects",
        summary = "List all projects",
        description = "Returns all projects the current user has access to.",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of projects", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ProjectResponse.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProjectsApi.PATH_LIST_PROJECTS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<Flux<ProjectResponse>>> listProjects(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_REMOVE_PROJECT_MEMBER = "/api/v1/projects/{projectId}/members/{userId}";
    /**
     * DELETE /api/v1/projects/{projectId}/members/{userId} : Remove a member from a project
     *
     * @param projectId  (required)
     * @param userId  (required)
     * @return Member removed (status code 204)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "removeProjectMember",
        summary = "Remove a member from a project",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Member removed"),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ProjectsApi.PATH_REMOVE_PROJECT_MEMBER,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> removeProjectMember(
        @Parameter(name = "projectId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") String userId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_PROJECT_MEMBER = "/api/v1/projects/{projectId}/members/{userId}";
    /**
     * PUT /api/v1/projects/{projectId}/members/{userId} : Update a project member&#39;s role
     *
     * @param projectId  (required)
     * @param userId  (required)
     * @param updateMemberRequest  (required)
     * @return Member updated (status code 200)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "updateProjectMember",
        summary = "Update a project member's role",
        tags = { "Projects" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Member updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProjectMemberResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProjectMemberResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ProjectsApi.PATH_UPDATE_PROJECT_MEMBER,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<ProjectMemberResponse>> updateProjectMember(
        @Parameter(name = "projectId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") String userId,
        @Parameter(name = "UpdateMemberRequest", description = "", required = true) @Valid @RequestBody Mono<UpdateMemberRequest> updateMemberRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
