/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.CreatePromptRequest;
import com.promptly.infrastructure.in.web.dto.GenerateFromIdeaRequest;
import com.promptly.infrastructure.in.web.dto.GenerateFromIdeaResponse;
import org.jspecify.annotations.Nullable;
import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import com.promptly.infrastructure.in.web.dto.PromptResponse;
import com.promptly.infrastructure.in.web.dto.PromptSummaryResponse;
import com.promptly.infrastructure.in.web.dto.UpdatePromptRequest;
import com.promptly.infrastructure.in.web.dto.VersionResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-05T23:45:25.362554800-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Prompts", description = "Prompt Registry — CRUD, versioning, and rollback")
public interface PromptsApi {

    String PATH_CREATE_PROMPT = "/api/v1/prompts";
    /**
     * POST /api/v1/prompts : Create a new prompt
     * Creates a new prompt with version 1. Emits &#x60;PromptCreated&#x60; event which triggers auto-scan and embedding generation.
     *
     * @param createPromptRequest  (required)
     * @return Prompt created successfully (status code 201)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     *         or An unexpected error occurred on the server (status code 500)
     */
    @Operation(
        operationId = "createPrompt",
        summary = "Create a new prompt",
        description = "Creates a new prompt with version 1. Emits `PromptCreated` event which triggers auto-scan and embedding generation.",
        tags = { "Prompts" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Prompt created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PromptResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PromptResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            }),
            @ApiResponse(responseCode = "500", description = "An unexpected error occurred on the server", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PromptsApi.PATH_CREATE_PROMPT,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<PromptResponse>> createPrompt(
        @Parameter(name = "CreatePromptRequest", description = "", required = true) @Valid @RequestBody Mono<CreatePromptRequest> createPromptRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_DELETE_PROMPT = "/api/v1/prompts/{id}";
    /**
     * DELETE /api/v1/prompts/{id} : Delete a prompt
     * Permanently deletes a prompt and all its versions.
     *
     * @param id Unique prompt identifier (required)
     * @return Prompt deleted (status code 204)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "deletePrompt",
        summary = "Delete a prompt",
        description = "Permanently deletes a prompt and all its versions.",
        tags = { "Prompts" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Prompt deleted"),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = PromptsApi.PATH_DELETE_PROMPT,
        produces = { "application/problem+json" }
    )
    Mono<ResponseEntity<Void>> deletePrompt(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GENERATE_FROM_IDEA = "/api/v1/prompts/generate";
    /**
     * POST /api/v1/prompts/generate : Generate a prompt from a natural-language idea
     * Uses a dedicated LLM system prompt to transform a short idea description into a fully-structured AI prompt. Unlike the improve endpoint, this does not require an existing prompt — it creates content from scratch. 
     *
     * @param generateFromIdeaRequest  (required)
     * @return Generated prompt content (status code 200)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     */
    @Operation(
        operationId = "generateFromIdea",
        summary = "Generate a prompt from a natural-language idea",
        description = "Uses a dedicated LLM system prompt to transform a short idea description into a fully-structured AI prompt. Unlike the improve endpoint, this does not require an existing prompt — it creates content from scratch. ",
        tags = { "Prompts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Generated prompt content", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GenerateFromIdeaResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = GenerateFromIdeaResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PromptsApi.PATH_GENERATE_FROM_IDEA,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<GenerateFromIdeaResponse>> generateFromIdea(
        @Parameter(name = "GenerateFromIdeaRequest", description = "", required = true) @Valid @RequestBody Mono<GenerateFromIdeaRequest> generateFromIdeaRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_PROMPT = "/api/v1/prompts/{id}";
    /**
     * GET /api/v1/prompts/{id} : Get prompt details
     * Returns full prompt details including latest content, tags, and timestamps.
     *
     * @param id Unique prompt identifier (required)
     * @return Prompt details (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "getPrompt",
        summary = "Get prompt details",
        description = "Returns full prompt details including latest content, tags, and timestamps.",
        tags = { "Prompts", "PromptlyQuery" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Prompt details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PromptResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PromptResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PromptsApi.PATH_GET_PROMPT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<PromptResponse>> getPrompt(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_SPECIFIC_VERSION = "/api/v1/prompts/{id}/versions/{versionNumber}";
    /**
     * GET /api/v1/prompts/{id}/versions/{versionNumber} : Get a specific version
     * Returns the content and metadata of a specific prompt version.
     *
     * @param id Unique prompt identifier (required)
     * @param versionNumber  (required)
     * @return Version details (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "getSpecificVersion",
        summary = "Get a specific version",
        description = "Returns the content and metadata of a specific prompt version.",
        tags = { "Prompts", "PromptlyQuery" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Version details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = VersionResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = VersionResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PromptsApi.PATH_GET_SPECIFIC_VERSION,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<VersionResponse>> getSpecificVersion(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Min(value = 1) @Parameter(name = "versionNumber", description = "", required = true, in = ParameterIn.PATH) @PathVariable("versionNumber") Integer versionNumber,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_VERSION_HISTORY = "/api/v1/prompts/{id}/versions";
    /**
     * GET /api/v1/prompts/{id}/versions : Get version history
     * Returns all versions of a prompt, ordered by version number.
     *
     * @param id Unique prompt identifier (required)
     * @return Version history (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "getVersionHistory",
        summary = "Get version history",
        description = "Returns all versions of a prompt, ordered by version number.",
        tags = { "Prompts", "PromptlyQuery" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Version history", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VersionResponse.class))),
                @Content(mediaType = "application/problem+json", array = @ArraySchema(schema = @Schema(implementation = VersionResponse.class)))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PromptsApi.PATH_GET_VERSION_HISTORY,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<Flux<VersionResponse>>> getVersionHistory(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_LIST_PROMPTS = "/api/v1/prompts";
    /**
     * GET /api/v1/prompts : List prompts (paginated)
     * Returns a paginated, streaming list of prompt summaries. Optionally filter by project ID.
     *
     * @param projectId Filter prompts by project ID (optional)
     * @param page Page number (0-indexed) (optional, default to 0)
     * @param size Number of items per page (optional, default to 20)
     * @param sort Sort criteria (e.g. createdAt,desc) (optional)
     * @return List of prompt summaries (status code 200)
     */
    @Operation(
        operationId = "listPrompts",
        summary = "List prompts (paginated)",
        description = "Returns a paginated, streaming list of prompt summaries. Optionally filter by project ID.",
        tags = { "Prompts", "PromptlyQuery" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of prompt summaries", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = PromptSummaryResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PromptsApi.PATH_LIST_PROMPTS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<Flux<PromptSummaryResponse>>> listPrompts(
        @Parameter(name = "projectId", description = "Filter prompts by project ID", in = ParameterIn.QUERY) @Valid @RequestParam(value = "projectId", required = false) @Nullable String projectId,
        @Min(value = 0) @Parameter(name = "page", description = "Page number (0-indexed)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "size", description = "Number of items per page", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "sort", description = "Sort criteria (e.g. createdAt,desc)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_ROLLBACK_PROMPT = "/api/v1/prompts/{id}/rollback/{targetVersion}";
    /**
     * POST /api/v1/prompts/{id}/rollback/{targetVersion} : Rollback to a previous version
     * Restores prompt content from a previous version and creates a new version with that content. Emits &#x60;PromptRolledBack&#x60; event.
     *
     * @param id Unique prompt identifier (required)
     * @param targetVersion  (required)
     * @param author  (optional, default to system)
     * @return Prompt rolled back (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "rollbackPrompt",
        summary = "Rollback to a previous version",
        description = "Restores prompt content from a previous version and creates a new version with that content. Emits `PromptRolledBack` event.",
        tags = { "Prompts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Prompt rolled back", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PromptResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PromptResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PromptsApi.PATH_ROLLBACK_PROMPT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<PromptResponse>> rollbackPrompt(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Min(value = 1) @Parameter(name = "targetVersion", description = "", required = true, in = ParameterIn.PATH) @PathVariable("targetVersion") Integer targetVersion,
        @Parameter(name = "author", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "author", required = false, defaultValue = "system") String author,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_UPDATE_PROMPT = "/api/v1/prompts/{id}";
    /**
     * PUT /api/v1/prompts/{id} : Update prompt content
     * Creates a new version of the prompt with updated content. Emits &#x60;PromptUpdated&#x60; event which triggers auto-scan and embedding refresh.
     *
     * @param id Unique prompt identifier (required)
     * @param updatePromptRequest  (required)
     * @return Prompt updated with new version (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "updatePrompt",
        summary = "Update prompt content",
        description = "Creates a new version of the prompt with updated content. Emits `PromptUpdated` event which triggers auto-scan and embedding refresh.",
        tags = { "Prompts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Prompt updated with new version", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PromptResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = PromptResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = PromptsApi.PATH_UPDATE_PROMPT,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<PromptResponse>> updatePrompt(
        @Parameter(name = "id", description = "Unique prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "UpdatePromptRequest", description = "", required = true) @Valid @RequestBody Mono<UpdatePromptRequest> updatePromptRequest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
