/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.promptly.infrastructure.in.web.api;

import com.promptly.infrastructure.in.web.dto.ProblemDetails;
import com.promptly.infrastructure.in.web.dto.ScanResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-23T20:26:14.636453-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Scanner", description = "Vulnerability Scanner — LLM-powered prompt security analysis")
public interface ScannerApi {

    String PATH_GET_ALL_SCANS = "/api/v1/scans";
    /**
     * GET /api/v1/scans : List all scan results
     * Returns all scan results across all prompts.
     *
     * @return List of scan results (status code 200)
     */
    @Operation(
        operationId = "getAllScans",
        summary = "List all scan results",
        description = "Returns all scan results across all prompts.",
        tags = { "Scanner" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of scan results", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ScanResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ScannerApi.PATH_GET_ALL_SCANS,
        produces = { "application/json" }
    )
    Mono<ResponseEntity<Flux<ScanResponse>>> getAllScans(
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_GET_LATEST_SCAN_RESULT = "/api/v1/prompts/{promptId}/scan-results";
    /**
     * GET /api/v1/prompts/{promptId}/scan-results : Get latest scan result
     * Returns the most recent scan result for a prompt.
     *
     * @param promptId Prompt identifier (required)
     * @return Latest scan result (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "getLatestScanResult",
        summary = "Get latest scan result",
        description = "Returns the most recent scan result for a prompt.",
        tags = { "Scanner" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Latest scan result", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ScanResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ScanResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ScannerApi.PATH_GET_LATEST_SCAN_RESULT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ScanResponse>> getLatestScanResult(
        @Parameter(name = "promptId", description = "Prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("promptId") String promptId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_TRIGGER_SCAN = "/api/v1/prompts/{promptId}/scan";
    /**
     * POST /api/v1/prompts/{promptId}/scan : Trigger a vulnerability scan
     * Runs an LLM-powered vulnerability analysis on the prompt&#39;s latest version.
     *
     * @param promptId Prompt identifier (required)
     * @return Scan results (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "triggerScan",
        summary = "Trigger a vulnerability scan",
        description = "Runs an LLM-powered vulnerability analysis on the prompt's latest version.",
        tags = { "Scanner" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Scan results", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ScanResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ScanResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ScannerApi.PATH_TRIGGER_SCAN,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ScanResponse>> triggerScan(
        @Parameter(name = "promptId", description = "Prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("promptId") String promptId,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
