/*
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spectrayan.promptly.query.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProjectResponse
 */
@JsonPropertyOrder({
  ProjectResponse.JSON_PROPERTY_ID,
  ProjectResponse.JSON_PROPERTY_NAME,
  ProjectResponse.JSON_PROPERTY_DESCRIPTION,
  ProjectResponse.JSON_PROPERTY_TAGS,
  ProjectResponse.JSON_PROPERTY_MEMBER_COUNT,
  ProjectResponse.JSON_PROPERTY_PROMPT_COUNT,
  ProjectResponse.JSON_PROPERTY_CREATED_BY,
  ProjectResponse.JSON_PROPERTY_CREATED_AT,
  ProjectResponse.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T16:30:36.848011900-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
public class ProjectResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_MEMBER_COUNT = "memberCount";
  @jakarta.annotation.Nullable
  private Integer memberCount;

  public static final String JSON_PROPERTY_PROMPT_COUNT = "promptCount";
  @jakarta.annotation.Nullable
  private Integer promptCount;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  @jakarta.annotation.Nonnull
  private String createdBy;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public ProjectResponse() {
  }

  public ProjectResponse id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public ProjectResponse name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public ProjectResponse description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public ProjectResponse tags(@jakarta.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public ProjectResponse addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }

  public ProjectResponse memberCount(@jakarta.annotation.Nullable Integer memberCount) {
    
    this.memberCount = memberCount;
    return this;
  }

  /**
   * Number of members in this project
   * @return memberCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMBER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemberCount() {
    return memberCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMBER_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberCount(@jakarta.annotation.Nullable Integer memberCount) {
    this.memberCount = memberCount;
  }

  public ProjectResponse promptCount(@jakarta.annotation.Nullable Integer promptCount) {
    
    this.promptCount = promptCount;
    return this;
  }

  /**
   * Number of prompts in this project
   * @return promptCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROMPT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPromptCount() {
    return promptCount;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromptCount(@jakarta.annotation.Nullable Integer promptCount) {
    this.promptCount = promptCount;
  }

  public ProjectResponse createdBy(@jakarta.annotation.Nonnull String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(@jakarta.annotation.Nonnull String createdBy) {
    this.createdBy = createdBy;
  }

  public ProjectResponse createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ProjectResponse updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectResponse projectResponse = (ProjectResponse) o;
    return Objects.equals(this.id, projectResponse.id) &&
        Objects.equals(this.name, projectResponse.name) &&
        Objects.equals(this.description, projectResponse.description) &&
        Objects.equals(this.tags, projectResponse.tags) &&
        Objects.equals(this.memberCount, projectResponse.memberCount) &&
        Objects.equals(this.promptCount, projectResponse.promptCount) &&
        Objects.equals(this.createdBy, projectResponse.createdBy) &&
        Objects.equals(this.createdAt, projectResponse.createdAt) &&
        Objects.equals(this.updatedAt, projectResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, tags, memberCount, promptCount, createdBy, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    memberCount: ").append(toIndentedString(memberCount)).append("\n");
    sb.append("    promptCount: ").append(toIndentedString(promptCount)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

