/*
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spectrayan.promptly.query.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.spectrayan.promptly.query.model.ContentFormat;
import com.spectrayan.promptly.query.model.PromptStatus;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PromptResponse
 */
@JsonPropertyOrder({
  PromptResponse.JSON_PROPERTY_ID,
  PromptResponse.JSON_PROPERTY_NAME,
  PromptResponse.JSON_PROPERTY_DESCRIPTION,
  PromptResponse.JSON_PROPERTY_PROJECT_ID,
  PromptResponse.JSON_PROPERTY_STATUS,
  PromptResponse.JSON_PROPERTY_CONTENT_FORMAT,
  PromptResponse.JSON_PROPERTY_CURRENT_VERSION,
  PromptResponse.JSON_PROPERTY_LATEST_CONTENT,
  PromptResponse.JSON_PROPERTY_TAGS,
  PromptResponse.JSON_PROPERTY_CREATED_AT,
  PromptResponse.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T16:30:36.848011900-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
public class PromptResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nullable
  private String projectId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private PromptStatus status;

  public static final String JSON_PROPERTY_CONTENT_FORMAT = "contentFormat";
  @jakarta.annotation.Nullable
  private ContentFormat contentFormat;

  public static final String JSON_PROPERTY_CURRENT_VERSION = "currentVersion";
  @jakarta.annotation.Nullable
  private Integer currentVersion;

  public static final String JSON_PROPERTY_LATEST_CONTENT = "latestContent";
  @jakarta.annotation.Nullable
  private String latestContent;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public PromptResponse() {
  }

  public PromptResponse id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique prompt ID (MongoDB ObjectId)
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public PromptResponse name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public PromptResponse description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public PromptResponse projectId(@jakarta.annotation.Nullable String projectId) {
    
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable String projectId) {
    this.projectId = projectId;
  }

  public PromptResponse status(@jakarta.annotation.Nullable PromptStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PromptStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable PromptStatus status) {
    this.status = status;
  }

  public PromptResponse contentFormat(@jakarta.annotation.Nullable ContentFormat contentFormat) {
    
    this.contentFormat = contentFormat;
    return this;
  }

  /**
   * Get contentFormat
   * @return contentFormat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContentFormat getContentFormat() {
    return contentFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentFormat(@jakarta.annotation.Nullable ContentFormat contentFormat) {
    this.contentFormat = contentFormat;
  }

  public PromptResponse currentVersion(@jakarta.annotation.Nullable Integer currentVersion) {
    
    this.currentVersion = currentVersion;
    return this;
  }

  /**
   * Latest version number
   * @return currentVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENT_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurrentVersion() {
    return currentVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENT_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentVersion(@jakarta.annotation.Nullable Integer currentVersion) {
    this.currentVersion = currentVersion;
  }

  public PromptResponse latestContent(@jakarta.annotation.Nullable String latestContent) {
    
    this.latestContent = latestContent;
    return this;
  }

  /**
   * Content of the latest version
   * @return latestContent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestContent() {
    return latestContent;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestContent(@jakarta.annotation.Nullable String latestContent) {
    this.latestContent = latestContent;
  }

  public PromptResponse tags(@jakarta.annotation.Nullable List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public PromptResponse addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }

  public PromptResponse createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public PromptResponse updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptResponse promptResponse = (PromptResponse) o;
    return Objects.equals(this.id, promptResponse.id) &&
        Objects.equals(this.name, promptResponse.name) &&
        Objects.equals(this.description, promptResponse.description) &&
        Objects.equals(this.projectId, promptResponse.projectId) &&
        Objects.equals(this.status, promptResponse.status) &&
        Objects.equals(this.contentFormat, promptResponse.contentFormat) &&
        Objects.equals(this.currentVersion, promptResponse.currentVersion) &&
        Objects.equals(this.latestContent, promptResponse.latestContent) &&
        Objects.equals(this.tags, promptResponse.tags) &&
        Objects.equals(this.createdAt, promptResponse.createdAt) &&
        Objects.equals(this.updatedAt, promptResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, projectId, status, contentFormat, currentVersion, latestContent, tags, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    contentFormat: ").append(toIndentedString(contentFormat)).append("\n");
    sb.append("    currentVersion: ").append(toIndentedString(currentVersion)).append("\n");
    sb.append("    latestContent: ").append(toIndentedString(latestContent)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

