/*
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptly.query.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Field-level validation error details
 */
@JsonPropertyOrder({
  ValidationError.JSON_PROPERTY_FIELD,
  ValidationError.JSON_PROPERTY_MESSAGE,
  ValidationError.JSON_PROPERTY_REJECTED_VALUE,
  ValidationError.JSON_PROPERTY_CODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T16:30:36.848011900-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
public class ValidationError {
  public static final String JSON_PROPERTY_FIELD = "field";
  @jakarta.annotation.Nonnull
  private String field;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_REJECTED_VALUE = "rejectedValue";
  @jakarta.annotation.Nullable
  private String rejectedValue;

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private String code;

  public ValidationError() {
  }

  public ValidationError field(@jakarta.annotation.Nonnull String field) {
    
    this.field = field;
    return this;
  }

  /**
   * Name of the field that failed validation
   * @return field
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIELD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getField() {
    return field;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setField(@jakarta.annotation.Nonnull String field) {
    this.field = field;
  }

  public ValidationError message(@jakarta.annotation.Nonnull String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Validation error message for this field
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public ValidationError rejectedValue(@jakarta.annotation.Nullable String rejectedValue) {
    
    this.rejectedValue = rejectedValue;
    return this;
  }

  /**
   * The value that was rejected (may be null)
   * @return rejectedValue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REJECTED_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectedValue() {
    return rejectedValue;
  }


  @JsonProperty(value = JSON_PROPERTY_REJECTED_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectedValue(@jakarta.annotation.Nullable String rejectedValue) {
    this.rejectedValue = rejectedValue;
  }

  public ValidationError code(@jakarta.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Machine-readable error code for this field
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable String code) {
    this.code = code;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationError validationError = (ValidationError) o;
    return Objects.equals(this.field, validationError.field) &&
        Objects.equals(this.message, validationError.message) &&
        Objects.equals(this.rejectedValue, validationError.rejectedValue) &&
        Objects.equals(this.code, validationError.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, message, rejectedValue, code);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationError {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    rejectedValue: ").append(toIndentedString(rejectedValue)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

