/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.spectrayan.promptly.infrastructure.in.web.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.spectrayan.promptly.infrastructure.in.web.dto.ExportManifest;
import com.spectrayan.promptly.infrastructure.in.web.dto.ImportResultResponse;
import org.jspecify.annotations.Nullable;
import java.time.OffsetDateTime;
import com.spectrayan.promptly.infrastructure.in.web.dto.ProblemDetails;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-05T23:45:25.362554800-05:00[America/Chicago]", comments = "Generator version: 7.21.0")
@Validated
@Tag(name = "Exchange", description = "Exchange — Import and export prompt manifests")
public interface ExchangeApi {

    String PATH_EXPORT_BY_PROJECT = "/api/v1/exchange/export/projects/{projectId}";
    /**
     * GET /api/v1/exchange/export/projects/{projectId} : Export prompts by project
     * Export all prompts in a project with optional date filters.
     *
     * @param projectId  (required)
     * @param approvedAfter  (optional)
     * @param approvedBefore  (optional)
     * @param xExportedBy  (optional, default to api)
     * @return Project prompts exported successfully (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "exportByProject",
        summary = "Export prompts by project",
        description = "Export all prompts in a project with optional date filters.",
        tags = { "Exchange" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Project prompts exported successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExportManifest.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ExportManifest.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ExchangeApi.PATH_EXPORT_BY_PROJECT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ExportManifest>> exportByProject(
        @Parameter(name = "projectId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("projectId") String projectId,
        @Parameter(name = "approvedAfter", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "approvedAfter", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime approvedAfter,
        @Parameter(name = "approvedBefore", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "approvedBefore", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @Nullable OffsetDateTime approvedBefore,
        @Parameter(name = "X-Exported-By", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-Exported-By", required = false, defaultValue = "api") String xExportedBy,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_EXPORT_PROMPT = "/api/v1/exchange/export/prompts/{promptId}";
    /**
     * GET /api/v1/exchange/export/prompts/{promptId} : Export a single prompt
     * Export a single prompt by its ID into a manifest.
     *
     * @param promptId Prompt identifier (required)
     * @param xExportedBy  (optional, default to api)
     * @return Prompt exported successfully (status code 200)
     *         or The requested resource was not found (status code 404)
     */
    @Operation(
        operationId = "exportPrompt",
        summary = "Export a single prompt",
        description = "Export a single prompt by its ID into a manifest.",
        tags = { "Exchange" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Prompt exported successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExportManifest.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ExportManifest.class))
            }),
            @ApiResponse(responseCode = "404", description = "The requested resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ExchangeApi.PATH_EXPORT_PROMPT,
        produces = { "application/json", "application/problem+json" }
    )
    Mono<ResponseEntity<ExportManifest>> exportPrompt(
        @Parameter(name = "promptId", description = "Prompt identifier", required = true, in = ParameterIn.PATH) @PathVariable("promptId") String promptId,
        @Parameter(name = "X-Exported-By", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-Exported-By", required = false, defaultValue = "api") String xExportedBy,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );


    String PATH_IMPORT_MANIFEST = "/api/v1/exchange/import";
    /**
     * POST /api/v1/exchange/import : Import prompts
     * Import prompts from an export manifest. Validates checksum integrity before applying.
     *
     * @param exportManifest  (required)
     * @return Import operation result (status code 200)
     *         or The request was invalid or malformed (validation errors, missing required fields, etc.) (status code 400)
     */
    @Operation(
        operationId = "importManifest",
        summary = "Import prompts",
        description = "Import prompts from an export manifest. Validates checksum integrity before applying.",
        tags = { "Exchange" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Import operation result", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ImportResultResponse.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ImportResultResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "The request was invalid or malformed (validation errors, missing required fields, etc.)", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProblemDetails.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = ProblemDetails.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ExchangeApi.PATH_IMPORT_MANIFEST,
        produces = { "application/json", "application/problem+json" },
        consumes = { "application/json" }
    )
    Mono<ResponseEntity<ImportResultResponse>> importManifest(
        @Parameter(name = "ExportManifest", description = "", required = true) @Valid @RequestBody Mono<ExportManifest> exportManifest,
        @Parameter(hidden = true) final ServerWebExchange exchange
    );

}
