/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Format of the prompt content
 * @export
 */
export const ContentFormat = {
    Text: 'TEXT',
    Json: 'JSON',
    Yaml: 'YAML',
    Markdown: 'MARKDOWN'
} as const;
export type ContentFormat = typeof ContentFormat[keyof typeof ContentFormat];


export function instanceOfContentFormat(value: any): boolean {
    for (const key in ContentFormat) {
        if (Object.prototype.hasOwnProperty.call(ContentFormat, key)) {
            if (ContentFormat[key as keyof typeof ContentFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentFormatFromJSON(json: any): ContentFormat {
    return ContentFormatFromJSONTyped(json, false);
}

export function ContentFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentFormat {
    return json as ContentFormat;
}

export function ContentFormatToJSON(value?: ContentFormat | null): any {
    return value as any;
}

export function ContentFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentFormat {
    return value as ContentFormat;
}

