/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryResponse
 */
export interface DeliveryResponse {
    /**
     * 
     * @type {string}
     * @memberof DeliveryResponse
     */
    promptId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryResponse
     */
    name?: string;
    /**
     * The full prompt content for runtime use
     * @type {string}
     * @memberof DeliveryResponse
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof DeliveryResponse
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof DeliveryResponse
     */
    contentFormat?: string;
}

/**
 * Check if a given object implements the DeliveryResponse interface.
 */
export function instanceOfDeliveryResponse(value: object): value is DeliveryResponse {
    return true;
}

export function DeliveryResponseFromJSON(json: any): DeliveryResponse {
    return DeliveryResponseFromJSONTyped(json, false);
}

export function DeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
        'name': json['name'] == null ? undefined : json['name'],
        'content': json['content'] == null ? undefined : json['content'],
        'version': json['version'] == null ? undefined : json['version'],
        'contentFormat': json['contentFormat'] == null ? undefined : json['contentFormat'],
    };
}

export function DeliveryResponseToJSON(json: any): DeliveryResponse {
    return DeliveryResponseToJSONTyped(json, false);
}

export function DeliveryResponseToJSONTyped(value?: DeliveryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'name': value['name'],
        'content': value['content'],
        'version': value['version'],
        'contentFormat': value['contentFormat'],
    };
}

