/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationError } from './ValidationError';
import {
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
    ValidationErrorToJSONTyped,
} from './ValidationError';

/**
 * RFC 9457 Problem Details for HTTP APIs — Standard error response format. Extension members (code, timestamp, traceId, errors) are permitted per §3.1.
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * URI reference identifying the problem type (§3.1.1)
     * @type {string}
     * @memberof ProblemDetails
     */
    type: string;
    /**
     * Short, human-readable summary of the problem type (§3.1.2)
     * @type {string}
     * @memberof ProblemDetails
     */
    title: string;
    /**
     * HTTP status code generated by the origin server for this occurrence (§3.1.3)
     * @type {number}
     * @memberof ProblemDetails
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence (§3.1.4)
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string;
    /**
     * URI reference identifying the specific occurrence of the problem (§3.1.5)
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: string;
    /**
     * Machine-readable error code for frontend error message mapping
     * @type {string}
     * @memberof ProblemDetails
     */
    code?: string;
    /**
     * Timestamp when the error occurred (ISO 8601 format)
     * @type {Date}
     * @memberof ProblemDetails
     */
    timestamp?: Date;
    /**
     * Unique trace ID for debugging and log correlation
     * @type {string}
     * @memberof ProblemDetails
     */
    traceId?: string;
    /**
     * Field-level validation errors (for 400 Bad Request responses)
     * @type {Array<ValidationError>}
     * @memberof ProblemDetails
     */
    errors?: Array<ValidationError>;
}

/**
 * Check if a given object implements the ProblemDetails interface.
 */
export function instanceOfProblemDetails(value: object): value is ProblemDetails {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProblemDetailsFromJSON(json: any): ProblemDetails {
    return ProblemDetailsFromJSONTyped(json, false);
}

export function ProblemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'code': json['code'] == null ? undefined : json['code'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ValidationErrorFromJSON)),
    };
}

export function ProblemDetailsToJSON(json: any): ProblemDetails {
    return ProblemDetailsToJSONTyped(json, false);
}

export function ProblemDetailsToJSONTyped(value?: ProblemDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'code': value['code'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'traceId': value['traceId'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ValidationErrorToJSON)),
    };
}

