/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectResponse
     */
    tags?: Array<string>;
    /**
     * Number of members in this project
     * @type {number}
     * @memberof ProjectResponse
     */
    memberCount?: number;
    /**
     * Number of prompts in this project
     * @type {number}
     * @memberof ProjectResponse
     */
    promptCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'promptCount': json['promptCount'] == null ? undefined : json['promptCount'],
        'createdBy': json['createdBy'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ProjectResponseToJSON(json: any): ProjectResponse {
    return ProjectResponseToJSONTyped(json, false);
}

export function ProjectResponseToJSONTyped(value?: ProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'tags': value['tags'],
        'memberCount': value['memberCount'],
        'promptCount': value['promptCount'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

