/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentFormat } from './ContentFormat';
import {
    ContentFormatFromJSON,
    ContentFormatFromJSONTyped,
    ContentFormatToJSON,
    ContentFormatToJSONTyped,
} from './ContentFormat';
import type { PromptStatus } from './PromptStatus';
import {
    PromptStatusFromJSON,
    PromptStatusFromJSONTyped,
    PromptStatusToJSON,
    PromptStatusToJSONTyped,
} from './PromptStatus';

/**
 * 
 * @export
 * @interface PromptResponse
 */
export interface PromptResponse {
    /**
     * Unique prompt ID (MongoDB ObjectId)
     * @type {string}
     * @memberof PromptResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PromptResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PromptResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PromptResponse
     */
    projectId?: string;
    /**
     * 
     * @type {PromptStatus}
     * @memberof PromptResponse
     */
    status?: PromptStatus;
    /**
     * 
     * @type {ContentFormat}
     * @memberof PromptResponse
     */
    contentFormat?: ContentFormat;
    /**
     * Latest version number
     * @type {number}
     * @memberof PromptResponse
     */
    currentVersion?: number;
    /**
     * Content of the latest version
     * @type {string}
     * @memberof PromptResponse
     */
    latestContent?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PromptResponse
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PromptResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PromptResponse
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the PromptResponse interface.
 */
export function instanceOfPromptResponse(value: object): value is PromptResponse {
    return true;
}

export function PromptResponseFromJSON(json: any): PromptResponse {
    return PromptResponseFromJSONTyped(json, false);
}

export function PromptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'status': json['status'] == null ? undefined : PromptStatusFromJSON(json['status']),
        'contentFormat': json['contentFormat'] == null ? undefined : ContentFormatFromJSON(json['contentFormat']),
        'currentVersion': json['currentVersion'] == null ? undefined : json['currentVersion'],
        'latestContent': json['latestContent'] == null ? undefined : json['latestContent'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PromptResponseToJSON(json: any): PromptResponse {
    return PromptResponseToJSONTyped(json, false);
}

export function PromptResponseToJSONTyped(value?: PromptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'projectId': value['projectId'],
        'status': PromptStatusToJSON(value['status']),
        'contentFormat': ContentFormatToJSON(value['contentFormat']),
        'currentVersion': value['currentVersion'],
        'latestContent': value['latestContent'],
        'tags': value['tags'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

