/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lifecycle status of a prompt
 * @export
 */
export const PromptStatus = {
    Draft: 'DRAFT',
    InReview: 'IN_REVIEW',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Deprecated: 'DEPRECATED'
} as const;
export type PromptStatus = typeof PromptStatus[keyof typeof PromptStatus];


export function instanceOfPromptStatus(value: any): boolean {
    for (const key in PromptStatus) {
        if (Object.prototype.hasOwnProperty.call(PromptStatus, key)) {
            if (PromptStatus[key as keyof typeof PromptStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PromptStatusFromJSON(json: any): PromptStatus {
    return PromptStatusFromJSONTyped(json, false);
}

export function PromptStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptStatus {
    return json as PromptStatus;
}

export function PromptStatusToJSON(value?: PromptStatus | null): any {
    return value as any;
}

export function PromptStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PromptStatus {
    return value as PromptStatus;
}

