/* tslint:disable */
/* eslint-disable */
/**
 * Promptly API
 * Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionResponse
 */
export interface VersionResponse {
    /**
     * 
     * @type {number}
     * @memberof VersionResponse
     */
    versionNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    changeMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof VersionResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the VersionResponse interface.
 */
export function instanceOfVersionResponse(value: object): value is VersionResponse {
    return true;
}

export function VersionResponseFromJSON(json: any): VersionResponse {
    return VersionResponseFromJSONTyped(json, false);
}

export function VersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'versionNumber': json['versionNumber'] == null ? undefined : json['versionNumber'],
        'content': json['content'] == null ? undefined : json['content'],
        'changeMessage': json['changeMessage'] == null ? undefined : json['changeMessage'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function VersionResponseToJSON(json: any): VersionResponse {
    return VersionResponseToJSONTyped(json, false);
}

export function VersionResponseToJSONTyped(value?: VersionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versionNumber': value['versionNumber'],
        'content': value['content'],
        'changeMessage': value['changeMessage'],
        'createdBy': value['createdBy'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

