# coding: utf-8

"""
    Promptly API

    Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ContentFormat(str, Enum):
    """
    Format of the prompt content
    """

    """
    allowed enum values
    """
    TEXT = 'TEXT'
    JSON = 'JSON'
    YAML = 'YAML'
    MARKDOWN = 'MARKDOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContentFormat from a JSON string"""
        return cls(json.loads(json_str))


