# coding: utf-8

"""
    Promptly API

    Enterprise AI Prompt Governance Platform — REST API  Promptly enables organizations to manage, version, secure, and deploy AI prompts with full governance controls. This specification covers all seven bounded contexts: Prompt Registry, Workflow Engine, Vulnerability Scanner, Quality Improver, Runtime Delivery, Audit & Compliance, and Semantic Search. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from promptly_query.models.validation_error import ValidationError
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProblemDetails(BaseModel):
    """
    RFC 9457 Problem Details for HTTP APIs — Standard error response format. Extension members (code, timestamp, traceId, errors) are permitted per §3.1.
    """ # noqa: E501
    type: StrictStr = Field(description="URI reference identifying the problem type (§3.1.1)")
    title: StrictStr = Field(description="Short, human-readable summary of the problem type (§3.1.2)")
    status: Annotated[int, Field(le=599, strict=True, ge=100)] = Field(description="HTTP status code generated by the origin server for this occurrence (§3.1.3)")
    detail: Optional[StrictStr] = Field(default=None, description="Human-readable explanation specific to this occurrence (§3.1.4)")
    instance: Optional[StrictStr] = Field(default=None, description="URI reference identifying the specific occurrence of the problem (§3.1.5)")
    code: Optional[StrictStr] = Field(default=None, description="Machine-readable error code for frontend error message mapping")
    timestamp: Optional[datetime] = Field(default=None, description="Timestamp when the error occurred (ISO 8601 format)")
    trace_id: Optional[StrictStr] = Field(default=None, description="Unique trace ID for debugging and log correlation", alias="traceId")
    errors: Optional[List[ValidationError]] = Field(default=None, description="Field-level validation errors (for 400 Bad Request responses)")
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "instance", "code", "timestamp", "traceId", "errors"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProblemDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item_errors in self.errors:
                if _item_errors:
                    _items.append(_item_errors.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProblemDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "instance": obj.get("instance"),
            "code": obj.get("code"),
            "timestamp": obj.get("timestamp"),
            "traceId": obj.get("traceId"),
            "errors": [ValidationError.from_dict(_item) for _item in obj["errors"]] if obj.get("errors") is not None else None
        })
        return _obj


