#!/usr/bin/env python3
"""
Post-processes bundled OpenAPI YAML to:
  Phase 1 — replace inline object schema $refs with canonical PascalCase names
  Phase 2 — replace inlined enum properties with $ref pointers

Usage: python3 deduplicate-schemas.py <path-to-bundled-openapi.yaml>
"""
import sys
import re
import yaml
from pathlib import Path
from collections import OrderedDict

# Preserve YAML ordering
def represent_ordereddict(dumper, data):
    return dumper.represent_mapping('tag:yaml.org,2002:map', data.items())

yaml.add_representer(OrderedDict, represent_ordereddict)

# Custom loader that preserves key order
class OrderedLoader(yaml.SafeLoader):
    pass

def construct_mapping(loader, node):
    loader.flatten_mapping(node)
    pairs = loader.construct_pairs(node)
    return OrderedDict(pairs)

OrderedLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    construct_mapping)


def get_property_signature(schema_def):
    """Get a sorted tuple of property names for a schema."""
    if not isinstance(schema_def, dict):
        return None
    props = schema_def.get('properties', {})
    if not props:
        return None
    return tuple(sorted(props.keys()))


def get_enum_signature(schema_def):
    """Get a sorted tuple of enum values for an enum schema."""
    if not isinstance(schema_def, dict):
        return None
    enum_vals = schema_def.get('enum')
    if not enum_vals:
        return None
    return tuple(sorted(enum_vals))


def is_canonical_name(name):
    """PascalCase names are canonical."""
    return name[0].isupper() if name else False


def is_inline_name(name):
    """snake_case names generated by the bundler are inline."""
    return name[0].islower() if name else False


def deep_replace_ref(obj, old_ref, new_ref):
    """Recursively replace $ref values in a nested structure."""
    if isinstance(obj, dict):
        result = OrderedDict()
        for k, v in obj.items():
            if k == '$ref' and v == old_ref:
                result[k] = new_ref
            else:
                result[k] = deep_replace_ref(v, old_ref, new_ref)
        return result
    elif isinstance(obj, list):
        return [deep_replace_ref(item, old_ref, new_ref) for item in obj]
    return obj


def main():
    if len(sys.argv) != 2:
        print("Usage: deduplicate-schemas.py <bundled-openapi.yaml>")
        sys.exit(1)

    spec_path = Path(sys.argv[1])
    if not spec_path.exists():
        print(f"Bundled spec not found at: {spec_path} — skipping deduplication")
        sys.exit(0)

    with open(spec_path, 'r') as f:
        spec = yaml.load(f, Loader=OrderedLoader)

    schemas = spec.get('components', {}).get('schemas', OrderedDict())

    canonical_schemas = {k: v for k, v in schemas.items() if is_canonical_name(k)}
    inline_schemas = {k: v for k, v in schemas.items() if is_inline_name(k)}

    print(f"Found {len(canonical_schemas)} canonical schemas, {len(inline_schemas)} inline schemas")

    # ── Phase 1: Match inline object schemas to canonical by property signature ──
    canonical_sigs = {}
    for name, schema_def in canonical_schemas.items():
        sig = get_property_signature(schema_def)
        if sig:
            canonical_sigs[sig] = name

    mappings = {}
    for inline_name, schema_def in inline_schemas.items():
        sig = get_property_signature(schema_def)
        if sig and sig in canonical_sigs:
            canonical_name = canonical_sigs[sig]
            mappings[inline_name] = canonical_name
            print(f"  Mapping: {inline_name} -> {canonical_name}")

    # Apply Phase 1 mappings
    for inline_name, canonical_name in mappings.items():
        old_ref = f"#/components/schemas/{inline_name}"
        new_ref = f"#/components/schemas/{canonical_name}"
        spec = deep_replace_ref(spec, old_ref, new_ref)
        # Remove the inline schema
        if inline_name in spec['components']['schemas']:
            del spec['components']['schemas'][inline_name]

    print(f"Phase 1: removed {len(mappings)} inline object schemas")

    # ── Phase 2: Replace inlined enum properties with $ref pointers ──
    schemas = spec.get('components', {}).get('schemas', OrderedDict())
    canonical_schemas = {k: v for k, v in schemas.items() if is_canonical_name(k)}

    canonical_enum_sigs = {}
    for name, schema_def in canonical_schemas.items():
        sig = get_enum_signature(schema_def)
        if sig:
            canonical_enum_sigs[sig] = name

    print(f"Found {len(canonical_enum_sigs)} canonical enum schemas")

    replaced_enums = 0

    def replace_inline_enums(obj):
        """Recursively replace inline enum definitions with $ref to canonical enum schema."""
        nonlocal replaced_enums
        if isinstance(obj, dict):
            result = OrderedDict()
            for k, v in obj.items():
                if isinstance(v, dict) and 'enum' in v and isinstance(v.get('enum'), list):
                    sig = tuple(sorted(v['enum']))
                    if sig in canonical_enum_sigs:
                        canonical_name = canonical_enum_sigs[sig]
                        result[k] = OrderedDict([('$ref', f"#/components/schemas/{canonical_name}")])
                        replaced_enums += 1
                        continue
                result[k] = replace_inline_enums(v)
            return result
        elif isinstance(obj, list):
            return [replace_inline_enums(item) for item in obj]
        return obj

    # Only replace within properties of schemas (not top-level enum schemas themselves)
    for schema_name, schema_def in list(schemas.items()):
        if isinstance(schema_def, dict) and 'properties' in schema_def:
            schemas[schema_name]['properties'] = replace_inline_enums(schema_def['properties'])

    print(f"Phase 2: replaced {replaced_enums} inlined enum properties with $ref pointers")

    # Write back
    with open(spec_path, 'w') as f:
        yaml.dump(spec, f, default_flow_style=False, allow_unicode=True, width=120)

    total = len(mappings) + replaced_enums
    print(f"Deduplication complete: {len(mappings)} inline schemas removed, {replaced_enums} enum refs restored")


if __name__ == '__main__':
    main()
